config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'houses#index'

  resources :houses do
    resources :characters do
      resources :tags
    end
  end
  get 'categories/:id' => 'categories#show', :as => :category_show

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    can :read, :all # permissions for every user, even if not logged in
    # can :manage, Fight
    can :manage, Tag
    if user.present?  # additional permissions for logged in users (they can manage their posts)
      can :manage, [House, Character], user_id: user.id
      # if user.admin  # additional permissions for administrators
      #   can :manage, :all
      # end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, {presence: true}
  has_many :tags, dependent: :destroy
  has_many :characters, through: :tags
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, {presence: true}
  belongs_to :house
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
end

app/models/house.rb
class House < ApplicationRecord
  validates :name, :motto, {presence: true}
  has_many :characters, dependent: :destroy
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :category
  belongs_to :character
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :characters, dependent: :destroy
  has_many :houses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @characters = @category.characters
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController


  def new
    @house = House.find(params[:house_id])
    @character = @house.characters.new
  end

  def show
    @house = House.find(params[:house_id])
    @character = Character.find(params[:id])
    @categories = @character.categories
    @tag = @character.tags.new
  end

  def create
    @house = House.find(params[:house_id])
    @character = @house.characters.create!(character_params.merge(user_id: current_user.id))
    flash[:notice] = "You successfully created the character #{@character.name}"
    redirect_to house_path(@house)
  end

  def edit
    @house = House.find(params[:house_id])
    @character = @house.characters.find(params[:id])
  end

  def update
    @house = House.find(params[:house_id])
    @character = @house.characters.find(params[:id])
    @character.update!(character_params)
    redirect_to house_path(@house)
  end

  def destroy
    @house = House.find(params[:house_id])
    @character = @house.characters.find(params[:id])
    @character.destroy
    redirect_to house_path(@house)
  end

  private

  def character_params
    params.require(:character).permit(:name)
  end



end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all
  end

  def new
    @house = House.new
  end

  def show
    @house = House.find(params[:id])
    @characters = @house.characters
  end

  def create
    @house = House.create!(house_params.merge(user_id: current_user.id))
    redirect_to houses_path
  end

  def edit
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    @house.update!(house_params)
    redirect_to houses_path
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    redirect_to houses_path
  end

  private

  def house_params
    params.require(:house).permit(:name, :motto)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


  def new
    @house = House.find(params[:house_id])
    @character = Character.find(params[:character_id])
    @tag = @character.tags.new
  end


  def create
    @character = Character.find(params[:character_id])
    @house = @character.house
    @name = tag_params[:category].titleize
    @category = Category.find_or_create_by(name: @name)
    if !@character.categories.find_by(name: @name)
      Tag.create(character: @character, category: @category)
    end
    redirect_to house_character_path(@house, @character)
  end


  private
  def tag_params
    params.require(:tag).permit(:category)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
  <% for character in @characters %>
    <li><%= character.name %></li>
  <% end %>
</ul>
<p><%= link_to "Back home", root_path %></p>

app/views/characters/edit.html.erb
<h1>Edit Character</h1>

<%= form_for [@house,@character] do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Update" %>

<% end %>

app/views/characters/new.html.erb
<h2>New Character for <%= @house.name %></h2>

<%= form_for [@house, @character] do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create" %>

<% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>
<ul>
  <% for category in @categories %>
    <li><%= link_to category.name, category_show_path(category) %></li>
  <% end %>
</ul>
<p><%= link_to "Add Tag", new_house_character_tag_path(@house, @character) %></p>
<% if can? :update, @character %>
  <p><%= link_to "Edit Character", edit_house_character_path(@house, @character) %></p>
  <p><%= link_to "Delete Character", house_character_path(@house, @character), method: :delete %></p>
<% end %>
<p><%= link_to "Back to House", house_path(@house) %></p>

app/views/houses/edit.html.erb
<h1>Edit House</h1>

<%= form_for @house do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :motto %>
  <%= f.text_field :motto %>

  <%= f.submit "Update" %>

<% end %>

app/views/houses/index.html.erb
<h1>Houses</h1>
<ul>
<% for house in @houses %>
  <li><%= link_to house.name, house_path(house) %></li>
<% end %>
</ul>
<p><%= link_to "New House", new_house_path %></p>

app/views/houses/new.html.erb
<h2>New House</h2>

<%= form_for [@house] do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :motto %>
  <%= f.text_field :motto %>

  <%= f.submit "Create" %>

<% end %>

app/views/houses/show.html.erb
<h1><%= @house.name %></h1>
<h2>Motto: <%= @house.motto %></h2>
<ul>
  <% for character in @characters %>
    <li><%= link_to character.name, house_character_path(@house,character) %></li>
  <% end %>
</ul>
<p><%= link_to "Add Character", new_house_character_path(@house) %></p>
<br>
<% if can? :update, @house %>
  <p><%= link_to "Edit House", edit_house_path(@house) %></p>
  <p><%= link_to "Delete House", house_path(@house), method: :delete %></p>
<% end %>
<p><%= link_to "Back to Houses", houses_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameofsloans</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if !current_user %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
      <% else %>
        <p><%= current_user.email %></p>
        <p><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></p>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <h1 align="center">Game of Thrones</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= form_for [@house,@character,@tag] do |f|  %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit "Submit" %>

<% end %>